using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EventType
{
    PLAY_RELOAD_ANIMATION,
    NO_PLAY_RELOAD_ANIMATION,
    PLAYER_HEALTH_CHANGED,
    PLAYER_DIED,
    QUEST_ACCEPTED,
    QUEST_PROGRESS_UPDATED,
    QUEST_COMPLETED,
    QUEST_FINISHED,
    NPC_DIALOG,
    NPC_QUEST_DIALOG,
    SHOP_OPENED,
    ITEM_PURCHASED,
    INVENTORY_UPDATED,
    GOLD_CHANGED,
}

